version: '3'
services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - mongo-db
  mongo-db:
    image: mongo:latest
    ports:
      - "27017:27017"
